# test、preview和master分支默认支持线上部署

stages:
  - build

# 每次开发新版本需要修改一下版本号
variables:
  PROJECT_VERSION: 0.0.1

# 安装依赖&&构建打包
build test:
  stage: build
  only:
    - test
  tags:
    - assets-deploy
  script:
    - cnpm i
    - npm run build:test
    - node ci.js $PROJECT_VERSION.$CI_COMMIT_SHORT_SHA.alpha 1 $(git log -1 --pretty=%B)

build preview:
  stage: build
  only:
    - preview
  tags:
    - assets-deploy
  script:
    - cnpm i
    - npm run build
    - node ci.js $PROJECT_VERSION.$CI_COMMIT_SHORT_SHA.beta 2 $(git log -1 --pretty=%B)

build prd:
  stage: build
  only:
    - master
  tags:
    - assets-deploy
  script:
    - cnpm i
    - npm run build
    - node ci.js $PROJECT_VERSION 3 $(git log -1 --pretty=%B)