# This is a basic workflow to help you get started with Actions

name: wx-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Runs a single command using the runners shell
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        env:
          MP_PRIVATE_KEY: ${{ secrets.MP_PRIVATE_KEY  }}
        run: |
          if [ ! $MP_PRIVATE_KEY ]; then
            echo "##########"
            echo ""
            echo "Please set 'MP_PRIVATE_KEY' key in actions secrets"
            echo ""
            echo "##########"
            exit 1
          else
            echo "$MP_PRIVATE_KEY" > private.wx.key
          fi
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          npm install
          npm run build
    # - name: set PRIVATE_KEY
    # - uses: actions/checkout@v2
    #   env:
    #     MP_PRIVATE_KEY: ${{ secrets.MP_PRIVATE_KEY  }}
    #   run: |
    #     if [ ! $MP_PRIVATE_KEY ]; then
    #         echo "##########"
    #         echo ""
    #         echo "Please set 'MP_PRIVATE_KEY' key in actions secrets"
    #         echo ""
    #         echo "##########"
    #         exit 1
    #       else
    #         echo "$MP_PRIVATE_KEY" > ci-private.key
    #       fi
    # Runs a set of commands using the runners shell
    # - name: upload wx-project
    #   run: |
    #     npm install
    #     npm run upload
